#!/bin/bash

start_dir=`pwd`
path1="$1"
path2="$2"
seed="$3"

cd $path1
make clean
make testdominion.out
./tests/testdominion $seed >> temp.out
gcov dominion.c >> temp.out

cd $path2
make clean
make testdominion.out
./tests/testdominion $seed >> temp.out
gcov dominion.c >> temp.out

cd $start_dir

diff -s -y $path1/temp.out $path2/temp.out >> diff
result=`tail -n 1 diff`
if [[ $result =~ .*identical.* ]];
then
    echo "TEST PASSED"
else
    cat diff
    echo "TEST FAILED"
fi
